# Generated by Django 6.1 on 2026-08-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=100)),
                ('descricao_banda', models.TextField(max_length=500)),
                ('demo_audio', models.FileField(blank=True, upload_to='demos/')),
                ('spotify', models.URLField(blank=True)),
                ('apple_music', models.URLField(blank=True)),
                ('youtube_music', models.URLField(blank=True)),
                ('amazon_music', models.URLField(blank=True)),
                ('deezer', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('x', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='banda/')),
            ],
        ),
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao_disco', models.TextField(max_length=500)),
                ('ano', models.PositiveIntegerField()),
                ('capa', models.ImageField(blank=True, upload_to='discos/')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discos', to='Projeto_Bandas.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('instrumento', models.CharField(max_length=100)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='Projeto_Bandas.banda')),
            ],
        ),
    ]
