# Generated by Django 6.1 on 2026-09-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Bandas', '0003_alter_banda_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='demo_audio',
            field=models.URLField(blank=True),
        ),
    ]
